steps:

- id: Download authentication
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -c
  - gcloud secrets versions access latest --secret=data-ingestion-secret > gcs_secret.json

- id: Build container image
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - -f
  - Dockerfile
  - -t
  - gcr.io/$PROJECT_ID/${_IMAGE_NAME_}:$BUILD_ID
  - '.'

- id: Push image to registry
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/peskas/${_IMAGE_NAME_}:$BUILD_ID

- id: Initialise incremental datasets
  name: gcr.io/peskas/${_IMAGE_NAME_}:$BUILD_ID
  entrypoint: Rscript
  args:
  - copy-objects.R
  env:
  - 'GCS_AUTH_FILE=gcs_secret.json'
  - 'ENV=prod'

timeout: 86400s

images:
- 'gcr.io/${PROJECT_ID}/ata-ingestion-objcopy:copying-$BUILD_ID'

substitutions:
  _IMAGE_NAME_: data-ingestion-objcopy
  _REGION_: asia-east1
