storage:
  provider: "google"
  bucket: 
    dev: "peskas-storage-dev"
    prod: "peskas-storage-prod"
  auth_file: "`r Sys.getenv('GCS_AUTH_FILE')`"

datasets:
  -
    interface: api
    source_agent: kobo
    data_format: json
    name: catch_timor_unstructured
    url: "https://kobo.humanitarianresponse.info/"
    encoding: "UTF-8"
    config:
      headers:
        Authorization: "`r readLines(Sys.getenv('KOBO_TOKEN_FILE'))`"
    path: 
      - api
      - v2
      - assets
      - aaztUDtRzb9SpSV7i9iptb # survey uid
      - data
  - 
    interface: api
    source_agent: kobo
    data_format: csv
    name: catch_timor_structured
    url: "https://kc.humanitarianresponse.info/"
    config:
      headers:
        Authorization: "`r readLines(Sys.getenv('KOBO_TOKEN_FILE'))`"
    path: 
      - api
      - v1
      - data
      - 344563 # survey id
    query:
      format: csv
