datasets:
  -
    interface: api
    source_agent: kobo
    data_format: json
    name: catch_timor_unstructured
    ingestion:
      type: all-data
    url: "https://kobo.humanitarianresponse.info/"
    encoding: "UTF-8"
    config:
      headers:
        Authorization: "`r readLines(Sys.getenv('KOBO_TOKEN_FILE'))`"
    path: 
      - api
      - v2
      - assets
      - aaztUDtRzb9SpSV7i9iptb # survey uid
      - data
    storage:
      provider: "google"
      bucket: 
        dev: "peskas-storage-dev"
        prod: "timor"
      auth_file: "`r Sys.getenv('GCS_AUTH_FILE')`"
  - 
    interface: api
    source_agent: kobo
    data_format: csv
    name: catch_timor_structured
    ingestion:
      type: all-data
    url: "https://kc.humanitarianresponse.info/"
    config:
      headers:
        Authorization: "`r readLines(Sys.getenv('KOBO_TOKEN_FILE'))`"
    path: 
      - api
      - v1
      - data
      - 344563 # survey id
    query:
      format: csv
    storage:
      provider: "google"
      bucket: 
        dev: "peskas-storage-dev"
        prod: "timor"
      auth_file: "`r Sys.getenv('GCS_AUTH_FILE')`"
  -
    interface: api
    source_agent: pelagic-data-systems
    data_format: csv
    name: pelagic-data
    overwrite: false
    ingestion:
      type: new-data
      name_append: "`r as.character(Sys.Date())`"
      download_historical: true
      start_date: "2018-02-08"
    url: "https://analytics.pelagicdata.com:443"
    config:
      headers: 
        X-API-SECRET: "`r yaml::read_yaml(Sys.getenv('PELAGIC_SECRET_FILE'))$SECRET`"
    path:
      - api
      - "`r yaml::read_yaml(Sys.getenv('PELAGIC_SECRET_FILE'))$API_KEY`"
      - v1
      - points
      - "`r as.character(Sys.Date()-1)`"
      - "`r as.character(Sys.Date())`"
    query:
      deviceInfo: true
    storage:
      provider: "google"
      bucket: 
        dev: "peskas-storage-dev"
        prod: "pelagic-data-systems-raw"
      auth_file: "`r Sys.getenv('GCS_AUTH_FILE')`"
